apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: app
data:
  POSTGRES_HOST: postgresql
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres