apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:14                 
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: db-init
              readOnly: true
            - mountPath: /var/lib/postgresql/data
              name: db-volume
      volumes:
        - name: db-init
          configMap:
            name: db-init
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-vclaim

