apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    ingester:
      wal:
        dir: /loki/wal
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      max_chunk_age: 1h

    schema_config:
      configs:
        - from: 2024-11-08
          store: boltdb-shipper
          object_store: filesystem
          schema: v13  # Updated to v13 for compatibility
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/boltdb-cache
      filesystem:
        directory: /loki/chunks

    limits_config:
      allow_structured_metadata: false  # Disables structured metadata

    compactor:
      working_directory: /loki/compactor  # Set working directory for compactor

