apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
      - name: promtail
        image: grafana/promtail:latest
        args:
          - -config.file=/etc/promtail/config.yaml
        volumeMounts:
          - name: config
            mountPath: /etc/promtail
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
        ports:
          - name: http
            containerPort: 9080
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
            type: Directory
