apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: app
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort