apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: "1"  # Required label for Grafana to pick it up
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: true
        uid: PBFA97CFB590B2093

      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        editable: true
        uid: P8E80F9AEF21F6940