apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grafana
  namespace: default
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
          name: web
        volumeMounts:
          - name: datasources-volume
            mountPath: /etc/grafana/provisioning/datasources  # Ruta para las fuentes de datos
          - name: dashboards-volume
            mountPath: /etc/grafana/provisioning/dashboards
          - name: grafana-storage
            mountPath: /var/lib/grafana
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
            claimName: grafana-pvc
      - name: datasources-volume
        configMap:
          name: grafana-datasources  # Nombre del ConfigMap para datasources
      - name: dashboards-volume
        configMap:
          name: grafana-dashboard