{
 "title": "Practica k8s",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Loki logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"docker_logs\"} |= ``"
    }
   ]
  },
  {
   "title": "app OK requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "flask_http_request_total{status=\"200\"}",
     "legendFormat": "App OK requests"
    }
   ]
  },
  {
   "title": "App status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "up{job=\"nginx\"}",
     "legendFormat": "1 = App is healthy"
    }
   ]
  },
  {
   "title": "Cache status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "up{job=\"redis\"}",
     "legendFormat": "1 = Redis is up"
    }
   ]
  },
  {
   "title": "DB status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "up{job=\"postgres\"}",
     "legendFormat": "1 = DB is up"
    }
   ]
  },
  { "title": "Services Down", "type": "alertlist", "gridPos": { "h": 9, "w": 5, "x": 18, "y": 13 } }
 ]
}