kind: ConfigMap
apiVersion: v1
metadata:
  name: db-init
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS items (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100),
        description TEXT
    );